---
- name: Vagrant provisioning using Ansible Playbook for Ubuntu 14.04
  hosts: all
  sudo: yes
  tasks:
    - name: install packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - wget
        - curl

    - name: isntall docker
      shell: curl -sSL https://get.docker.com/ | sh

    # required to install docker-py
    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python

    # required by ansible docker module
    - name: install docker-py
      pip: name=docker-py version=1.1.0 # v1.1.0 is workaround from https://github.com/ansible/ansible/issues/10879#issuecomment-97738264

    - name: pull nginx image
      command: docker pull nginx:latest

    - name: nginx container
      docker:
        image: nginx:latest
        name: my.nginx
        state: started
        ports:
          - "80:80"
          - "443:443"
