---
- name: Vagrant provisioning using Ansible Playbook for Ubuntu 14.04
  hosts: all
  sudo: yes
  tasks:
    - name: install packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - wget
        - curl

    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh
      args:
        creates: /usr/bin/docker

    # required to install docker-py
    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python
      args:
        creates: /usr/local/bin/pip

    # required by ansible docker module
    - name: install docker-py
      pip: name=docker-py version=1.1.0 # v1.1.0 is workaround from https://github.com/ansible/ansible/issues/10879#issuecomment-97738264

    - name: check or build nginx image
      docker_image:
        path: /vagrant/docker/nginx
        name: my.nginx
        state: build

    - name: nginx container
      docker:
        image: my.nginx
        name: my.nginx.container
        state: restarted
        ports:
          - "80:80"
          - "443:443"

    - name: check or build php-fpm image
      docker_image:
        path: /vagrant/docker/php-fpm
        name: my.php-fpm
        state: build

    - name: php-fpm container
      docker:
        image: php:fpm
        name: my.php-fpm.container
        state: restarted
        links:
          - "my.nginx.container"
        ports:
          - "9000:9000"
